### ISSUE TITLE
Test new Update.

### ISSUE THREAD

**Issue by fossil22** [koraykarakus/steemnova-1.8-x#15]
Under Admin Menu.
Butten universe configuration.
Error message.

Message: Unknown configuration key metal_start!
File: /includes/classes/Config.class.php
Line: 95
URL: https://mkmatz.eno-intern.de/b/admin.php?page=universe
PHP-Version: 8.2.9
PHP-API: fpm-fcgi
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/pages/adm/ShowUniversePage.class.php(103): Config->__get('metal_start')
#1 /admin.php(95): ShowUniversePage->show()
#2 {main}

**Comment by fossil22** [comment]
Test OK Fix Perfekt
