### ISSUE TITLE
File "overall_header.tpl" can not be loaded.

### ISSUE THREAD

**Issue by KidProtect** [koraykarakus/steemnova-1.8-x#2]
When opening the page for editing a planet in backend the following fatal error appears:

```
Message: Unable to load template 'file:overall_header.tpl'
File: /includes/libs/Smarty/libs/sysplugins/smarty_template_compiled.php
Line: 96
URL: http://game1.test/admin.php?page=quickEditor&mode=planet&id=1
PHP-Version: 8.2.11
PHP-API: fpm-fcgi
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/libs/Smarty/libs/sysplugins/smarty_internal_template.php(384): Smarty_Template_Compiled->render()
#1 /cache/en^ceadb0ef2eface1965898a382f3cb8f5bc7d2a74_1.file.QuickEditorPlanet.tpl.cache.php(33): Smarty_Internal_Template->_subTemplateRender()
#2 /includes/libs/Smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6520c3aac43c14_92271108()
#3 /includes/libs/Smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#4 /includes/libs/Smarty/libs/sysplugins/smarty_internal_runtime_updatecache.php(38): Smarty_Template_Compiled->render()
#5 /includes/libs/Smarty/libs/sysplugins/smarty_template_cached.php(143): Smarty_Internal_Runtime_UpdateCache->updateCache()
#6 /includes/libs/Smarty/libs/sysplugins/smarty_internal_template.php(212): Smarty_Template_Cached->render()
#7 /includes/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()
#8 /includes/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#9 /includes/classes/class.template.php(138): Smarty_Internal_TemplateBase->display()
#10 /includes/pages/adm/ShowQuickEditorPage.class.php(322): template->show()
#11 /admin.php(95): ShowQuickEditorPage->planet()
#12 {main}
```

**Comment by koraykarakus** [comment]
caused by old database, needs to reworked. For now it is fixed.
