### ISSUE TITLE
Error on Install Step 8 (MySQL)

### ISSUE THREAD

**Issue by w503v12** [koraykarakus/steemnova-1.8-x#5]
Hello, 

first of all thanks for the work you put into this already. 

I have a slight problem with the install scripts it seems, everything works fine until I get to the part where the intial database fill seems to happen. 

After confirming the information necessary for the admin user, I get this error:

`Message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system = '1' AND planet = '2' AND planet_type = '1'' at line 5

Query-Code:SELECT COUNT(*) as record FROM planets WHERE universe = 1 AND galaxy = 1 AND system = 1 AND planet = 2 AND planet_type = 1;
File: /includes/classes/Database.class.php
Line: 126
URL: http://192.168.178.152:4444/install/index.php?mode=install&step=8
PHP-Version: 8.2.7
PHP-API: fpm-fcgi
2Moons Version: 1.8.git (FILE)
Debug Backtrace:
#0 /includes/classes/Database.class.php(202): Database->_query('SELECT COUNT(*)...', Array, 'select')
#1 /includes/classes/PlayerUtil.class.php(36): Database->selectSingle('SELECT COUNT(*)...', Array, 'record')
#2 /includes/classes/PlayerUtil.class.php(88): PlayerUtil::isPositionFree(1, 1, 1, 2)
#3 /install/index.php(663): PlayerUtil::createPlayer(1, 'adminuser', 'randomsaltedstring.', 'mail@example.co...', 'de', 1, 1, 2, NULL, 3)
#4 {main}`

(cleaned up the creds there so don´t worry)

Here is the information from the requirements screen:
![image](https://github.com/koraykarakus/steemnova-1.8-x/assets/31518759/944c55f4-1343-46f3-a01c-32e401d7d4bf)

Currently running MySQL in version 8.2.0.

**Comment by w503v12** [comment]
Just tested it, works with MariaDB current version

**Comment by koraykarakus** [comment]
It might be caused by mysql version. Try using recommended mysql version for now, system keyword might be reserved on some versions of mysql. You can also try backticking system keyword on install.sql like `system`
